// Copyright 2017-2022 @bitriel/web-runner authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@bitriel/web-runner', path: 'auto', type: 'auto', version: '1.1.35-0' };
