// Copyright 2017-2022 @subwallet/subwallet-api-sdk authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/subwallet-api-sdk', path: 'auto', type: 'auto', version: '1.3.36-0' };
