// Copyright 2019-2022 @bitriel/extension-base
// SPDX-License-Identifier: Apache-2.0

import { SwapErrorType } from '../swap';

export enum YieldValidationStatus {
  NOT_ENOUGH_FEE = 'NOT_ENOUGH_FEE',
  NOT_ENOUGH_BALANCE = 'NOT_ENOUGH_BALANCE',
  NOT_ENOUGH_MIN_JOIN_POOL = 'NOT_ENOUGH_MIN_JOIN_POOL',
  OK = 'OK'
}

export enum BasicTxErrorType {
  NOT_ENOUGH_BALANCE = 'NOT_ENOUGH_BALANCE',
  CHAIN_DISCONNECTED = 'CHAIN_DISCONNECTED',
  INVALID_PARAMS = 'INVALID_PARAMS',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  UNABLE_TO_SIGN = 'UNABLE_TO_SIGN',
  USER_REJECT_REQUEST = 'USER_REJECT_REQUEST',
  UNABLE_TO_SEND = 'UNABLE_TO_SEND',
  SEND_TRANSACTION_FAILED = 'SEND_TRANSACTION_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNSUPPORTED = 'UNSUPPORTED',
  TIMEOUT = 'TIMEOUT',
  NOT_ENOUGH_EXISTENTIAL_DEPOSIT = 'NOT_ENOUGH_EXISTENTIAL_DEPOSIT',
}

export enum StakingTxErrorType {
  NOT_ENOUGH_MIN_STAKE = 'NOT_ENOUGH_MIN_STAKE',
  EXCEED_MAX_NOMINATIONS = 'EXCEED_MAX_NOMINATIONS',
  EXIST_UNSTAKING_REQUEST = 'EXIST_UNSTAKING_REQUEST',
  INVALID_ACTIVE_STAKE = 'INVALID_ACTIVE_STAKE',
  EXCEED_MAX_UNSTAKING = 'EXCEED_MAX_UNSTAKING',
  INACTIVE_NOMINATION_POOL = 'INACTIVE_NOMINATION_POOL',
  CAN_NOT_GET_METADATA = 'CAN_NOT_GET_METADATA',
  NOT_ENOUGH_MIN_UNSTAKE = 'NOT_ENOUGH_MIN_UNSTAKE'
}

export enum TransferTxErrorType {
  NOT_ENOUGH_VALUE = 'NOT_ENOUGH_VALUE',
  NOT_ENOUGH_FEE = 'NOT_ENOUGH_FEE',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TRANSFER_ERROR = 'TRANSFER_ERROR',
  RECEIVER_NOT_ENOUGH_EXISTENTIAL_DEPOSIT = 'RECEIVER_NOT_ENOUGH_EXISTENTIAL_DEPOSIT',
  RECEIVER_ACCOUNT_INACTIVE = 'RECEIVER_ACCOUNT_INACTIVE'
}

export type TransactionErrorType = BasicTxErrorType | TransferTxErrorType | StakingTxErrorType | YieldValidationStatus | SwapErrorType;
