// Copyright 2017-2022 @bitriel/extension-koni authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@bitriel/extension-koni', path: 'auto', type: 'auto', version: '1.0.2' };
