name: Build WebApp Preview
on:
  pull_request:
    branches:
      - webapp
      - webapp-dev
  push:
    branches:
      - webapp
      - webapp-dev
      - webapp-demo

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') || github.ref == 'refs/heads/webapp'"
    name: Deploy WebApp Preview
    runs-on: ubuntu-22.04
    environment: 'webapp'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - name: Build
      env:
        TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
        COINBASE_PAY_ID: ${{ secrets.COINBASE_PAY_ID }}
        NFT_MINTING_HOST: ${{ secrets.NFT_MINTING_HOST }}
        CHAINFLIP_BROKER_API: ${{ secrets.CHAINFLIP_BROKER_API }}
        BITTENSOR_API_KEY_1: ${{ secrets.BITTENSOR_API_KEY_1 }}
        BITTENSOR_API_KEY_2: ${{ secrets.BITTENSOR_API_KEY_2 }}
        BITTENSOR_API_KEY_3: ${{ secrets.BITTENSOR_API_KEY_3 }}
        BITTENSOR_API_KEY_4: ${{ secrets.BITTENSOR_API_KEY_4 }}
        BITTENSOR_API_KEY_5: ${{ secrets.BITTENSOR_API_KEY_5 }}
        BITTENSOR_API_KEY_6: ${{ secrets.BITTENSOR_API_KEY_6 }}
        BITTENSOR_API_KEY_7: ${{ secrets.BITTENSOR_API_KEY_7 }}
        BITTENSOR_API_KEY_8: ${{ secrets.BITTENSOR_API_KEY_8 }}
        BITTENSOR_API_KEY_9: ${{ secrets.BITTENSOR_API_KEY_9 }}
        BITTENSOR_API_KEY_10: ${{ secrets.BITTENSOR_API_KEY_10 }}
        SIMPLE_SWAP_API_KEY: ${{ secrets.SIMPLE_SWAP_API_KEY }}
        UNISWAP_API_KEY:  ${{ secrets.UNISWAP_API_KEY }}
        KYBER_CLIENT_ID: ${{ secrets.KYBER_CLIENT_ID }}
        SUBWALLET_API: ${{ secrets.SUBWALLET_API }}
        BLOCKFROST_API_KEY_MAIN: ${{ secrets.BLOCKFROST_API_KEY_MAIN }}
        BLOCKFROST_API_KEY_PREP: ${{ secrets.BLOCKFROST_API_KEY_PREP }}
        PARASPELL_API_KEY: ${{ secrets.PARASPELL_API_KEY }}
        MELD_API_KEY: ${{ secrets.MELD_API_KEY }}
        MELD_WIZARD_KEY: ${{ secrets.MELD_WIZARD_KEY }}
        BRANCH_NAME: ${{ github.ref_name }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        if [ ${{ github.ref_name }} == 'webapp-dev' ]; then
            yarn run webapp:change-build-number
        fi
        yarn webapp:build
    - name: Publish to Cloudflare Pages
      id: cloudflare_deployment
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
        gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
        branch: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref_name }}
        directory: './packages/webapp/build'
        wranglerVersion: '3'
    - if: "github.ref_name == 'webapp-dev' && github.event_name == 'push'"
      name: Automation Bot
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Automation Bot
        author_email: bot@subwallet.app
        message: '[CI Skip] Auto increase webapp build number'
    - name: Notify to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        username: WebApp Worker
        title: ${{ github.workflow }}
        description: |
          The deployment is completed.
            - URL: ${{ steps.cloudflare_deployment.outputs.url }}
            - Alias: ${{ steps.cloudflare_deployment.outputs.alias }}
